[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
actix-web = "4"
reqwest = "0.11.16"
serde = { version = "1.0.160", features = ["derive"]}
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
