application_settings:
  host: 0.0.0.0
  base_url: "https:/zero2prod-bniwl.ondigitalocean.app"
database:
  require_ssl: true
email_configuration: 
  base_url: "https://api.postmarkapp.com/email"
  sender_email: "kylemiller@kylemiller.io"
